/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#0a0a0a',
        surface: '#0f0f0f',
        'surface-dim': '#0f0f0f',
        'surface-bright': '#2a2a2a',
        'surface-container-lowest': '#0c0c0c',
        'surface-container-low': '#141414',
        'surface-container': '#1a1a1a',
        'surface-container-high': '#252525',
        'surface-container-highest': '#303030',
        'on-surface': '#f5f5f5',
        'on-surface-variant': '#d0d0d0',
        'inverse-surface': '#f5f5f5',
        'inverse-on-surface': '#1a1a1a',
        outline: '#7a7a7a',
        'outline-variant': '#505050',
        'surface-tint': '#0066ff',
        primary: '#0066ff',
        'on-primary': '#ffffff',
        'primary-container': '#0052cc',
        'on-primary-container': '#ffffff',
        'inverse-primary': '#66b3ff',
        secondary: '#2ff801',
        'on-secondary': '#000000',
        'secondary-container': '#00cc00',
        'on-secondary-container': '#ffffff',
        tertiary: '#c6c6c6',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#717272',
        'on-tertiary-container': '#f9f8f8',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#dae1ff',
        'primary-fixed-dim': '#b3c5ff',
        'on-primary-fixed': '#001849',
        'on-primary-fixed-variant': '#003fa4',
        'secondary-fixed': '#79ff5b',
        'secondary-fixed-dim': '#2ae500',
        'on-secondary-fixed': '#022100',
        'on-secondary-fixed-variant': '#095300',
        'tertiary-fixed': '#e3e2e2',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#464747',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
      },
      fontFamily: {
        sans: ["Geist", "var(--font-geist-sans)", "ui-sans-serif", "system-ui"],
        mono: ["JetBrains Mono", "var(--font-geist-mono)", "ui-monospace", "SFMono-Regular"],
        display: ["Geist", "sans-serif"],
        technical: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        'display-hero': '5rem',
        'headline-lg': '3rem',
        'body-md': '1rem',
        'technical-sm': '0.75rem',
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        'level-1': '0 8px 32px rgba(0, 102, 255, 0.15)',
        'level-2': 'inset 1px 1px 2px rgba(47, 248, 1, 0.1), inset -1px -1px 2px rgba(0, 0, 0, 0.5)',
        'glow-blue': '0 0 30px rgba(0, 102, 255, 0.6)',
        'glow-green': '0 0 30px rgba(47, 248, 1, 0.6)',
        'glow-blue-sm': '0 0 12px rgba(0, 102, 255, 0.4)',
        'glow-green-sm': '0 0 12px rgba(47, 248, 1, 0.4)',
      },
      animation: {
        'spin-slow': 'spin 20s linear infinite',
      },
    },
  },
  plugins: [],
}
