/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Theme-aware colors using CSS variables — DESIGN.md palette
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        'surface-dim': 'var(--color-surface-dim)',
        'surface-bright': 'var(--color-surface-bright)',
        'surface-container-lowest': 'var(--color-surface-container-lowest)',
        'surface-container-low': 'var(--color-surface-container-low)',
        'surface-container': 'var(--color-surface-container)',
        'surface-container-high': 'var(--color-surface-container-high)',
        'surface-container-highest': 'var(--color-surface-container-highest)',
        'on-surface': 'var(--color-on-surface)',
        'on-surface-variant': 'var(--color-on-surface-variant)',
        'inverse-surface': 'var(--color-inverse-surface)',
        'inverse-on-surface': 'var(--color-inverse-on-surface)',
        outline: 'var(--color-outline)',
        'outline-variant': 'var(--color-outline-variant)',
        'surface-variant': 'var(--color-surface-variant)',
        'on-background': 'var(--color-on-background)',

        // Semantic colors — Linked to CSS variables for theming
        'surface-tint': 'var(--color-primary)',
        primary: 'var(--color-primary)',
        'on-primary': 'var(--color-on-primary, #ffffff)',
        'primary-container': 'var(--color-primary-container, #a9583e)',
        'on-primary-container': 'var(--color-on-primary-container, #ffffff)',
        'inverse-primary': 'var(--color-inverse-primary, #e8a55a)',
        secondary: 'var(--color-secondary)',
        'on-secondary': 'var(--color-on-secondary, #ffffff)',
        'secondary-container': 'var(--color-secondary-container, #e8a55a)',
        'on-secondary-container': 'var(--color-on-secondary-container, #141413)',
        tertiary: 'var(--color-tertiary)',
        'on-tertiary': 'var(--color-on-tertiary, #141413)',
        'tertiary-container': 'var(--color-tertiary-container, #ebe6df)',
        'on-tertiary-container': 'var(--color-on-tertiary-container, #3d3d3a)',
        error: 'var(--color-error, #c64545)',
        'on-error': 'var(--color-on-error, #ffffff)',
        'error-container': 'var(--color-error-container, #f5d0cc)',
        'on-error-container': 'var(--color-on-error-container, #3d1010)',
        'primary-fixed': '#cc785c',
        'primary-fixed-dim': '#a9583e',
        'on-primary-fixed': '#ffffff',
        'on-primary-fixed-variant': '#a9583e',
        'secondary-fixed': '#5db8a6',
        'secondary-fixed-dim': '#4a9386',
        'on-secondary-fixed': '#ffffff',
        'on-secondary-fixed-variant': '#3d7566',
        'tertiary-fixed': '#e8e0d2',
        'tertiary-fixed-dim': '#d4cfc5',
        'on-tertiary-fixed': '#141413',
        'on-tertiary-fixed-variant': '#8b8782',
        success: '#5db872',
        warning: '#d4a017',
      },
      fontFamily: {
        sans: ["Inter", "var(--font-sans)", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "Roboto", "sans-serif"],
        mono: ["JetBrains Mono", "var(--font-mono)", "ui-monospace", "SFMono-Regular", "monospace"],
        display: ["Cormorant Garamond", "var(--font-display)", "Tiempos Headline", "Georgia", "serif"],
        technical: ["JetBrains Mono", "var(--font-mono)", "monospace"],
      },
      fontSize: {
        'display-xl': '48px',
        'display-lg': '36px',
        'display-hero': '5rem',
        'headline-lg': '3rem',
        'headline': '24px',
        'body-md': '1rem',
        'body-lg': '16px',
        'body-sm': '12px',
        'caption': '11px',
        'label': '12px',
        'technical-sm': '0.75rem',
      },
      fontWeight: {
        'hairline': 100,
        'thin': 200,
        'extralight': 300,
        'light': 300,
        'normal': 400,
        'medium': 500,
        'semibold': 600,
        'bold': 700,
        'extrabold': 800,
        'black': 900,
      },
      borderRadius: {
        'none': '0',
        'sm': '4px',
        'DEFAULT': '8px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
        'full': '9999px',
      },
      boxShadow: {
        'elevated-1': '0 1px 2px rgba(0, 0, 0, 0.05)',
        'elevated-2': '0 4px 6px rgba(0, 0, 0, 0.07)',
        'elevated-3': '0 10px 15px rgba(0, 0, 0, 0.1)',
        'elevated-4': '0 20px 25px rgba(0, 0, 0, 0.1)',
        'elevated-5': '0 25px 50px rgba(0, 0, 0, 0.15)',
        'level-1': '0 8px 32px rgba(0, 102, 255, 0.15)',
        'level-2': 'inset 1px 1px 2px rgba(47, 248, 1, 0.1), inset -1px -1px 2px rgba(0, 0, 0, 0.5)',
        'glow-blue': '0 0 30px rgba(0, 102, 255, 0.6)',
        'glow-blue-lg': '0 0 40px rgba(0, 102, 255, 0.5)',
        'glow-blue-sm': '0 0 12px rgba(0, 102, 255, 0.4)',
        'glow-green': '0 0 30px rgba(47, 248, 1, 0.6)',
        'glow-green-lg': '0 0 40px rgba(47, 248, 1, 0.5)',
        'glow-green-sm': '0 0 12px rgba(47, 248, 1, 0.4)',
        'focus-ring': '0 0 0 3px rgba(0, 102, 255, 0.1), 0 0 0 1px #0066FF',
        'focus-ring-error': '0 0 0 3px rgba(239, 68, 68, 0.1), 0 0 0 1px #EF4444',
      },
      spacing: {
        'xs': '4px',
        'sm': '8px',
        'md': '12px',
        'lg': '16px',
        'xl': '24px',
        'xxl': '32px',
        'xxxl': '48px',
      },
      animation: {
        'spin-slow': 'spin 20s linear infinite',
        'pulse-slow': 'pulse 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
      },
      lineHeight: {
        'tight': '1.2',
        'snug': '1.25',
        'normal': '1.5',
        'relaxed': '1.6',
        'loose': '2',
      },
      letterSpacing: {
        'tighter': '-0.02em',
        'tight': '-0.01em',
        'normal': '0',
        'wide': '0.01em',
        'wider': '0.02em',
        'widest': '0.3em',
      },
    },
  },
  plugins: [],
}
