/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        background: '#0a0a0a',
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#3a3939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#c2c6d8',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#8c90a1',
        'outline-variant': '#424656',
        'surface-tint': '#b3c5ff',
        primary: '#b3c5ff',
        'on-primary': '#002b75',
        'primary-container': '#0066ff',
        'on-primary-container': '#f8f7ff',
        'inverse-primary': '#0054d6',
        secondary: '#d7ffc5',
        'on-secondary': '#053900',
        'secondary-container': '#2ff801',
        'on-secondary-container': '#0f6d00',
        tertiary: '#c6c6c6',
        'on-tertiary': '#2f3131',
        'tertiary-container': '#717272',
        'on-tertiary-container': '#f9f8f8',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#dae1ff',
        'primary-fixed-dim': '#b3c5ff',
        'on-primary-fixed': '#001849',
        'on-primary-fixed-variant': '#003fa4',
        'secondary-fixed': '#79ff5b',
        'secondary-fixed-dim': '#2ae500',
        'on-secondary-fixed': '#022100',
        'on-secondary-fixed-variant': '#095300',
        'tertiary-fixed': '#e3e2e2',
        'tertiary-fixed-dim': '#c6c6c6',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#464747',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
      },
      fontFamily: {
        sans: ["Geist", "var(--font-geist-sans)", "ui-sans-serif", "system-ui"],
        mono: ["JetBrains Mono", "var(--font-geist-mono)", "ui-monospace", "SFMono-Regular"],
        display: ["Geist", "sans-serif"],
        technical: ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        'display-hero': '5rem',
        'headline-lg': '3rem',
        'body-md': '1rem',
        'technical-sm': '0.75rem',
      },
      borderRadius: {
        'sm': '0.125rem',
        'DEFAULT': '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      boxShadow: {
        'level-1': '0 4px 20px rgba(0,0,0,0.5)',
        'level-2': 'inset 1px 1px 1px rgba(255,255,255,0.05), inset -1px -1px 1px rgba(0,0,0,0.2)',
        'glow-blue': '0 0 20px rgba(0, 102, 255, 0.3)',
        'glow-green': '0 0 20px rgba(47, 248, 1, 0.3)',
      },
      animation: {
        'spin-slow': 'spin 20s linear infinite',
      },
    },
  },
  plugins: [],
}
